In [18]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier as mlp
import sklearn.metrics
from sklearn.model_selection import GridSearchCV

In [19]:
# Define functions and common variables
def create_output_file(y_actual, y_predicted, labels, filename):
    '''
    Function for creating the ouput file as specified in the assignment instructions:
    a) instance number and predicted label (number)
    b) Confusion matrix
    c) Precision, recall and f1-measure of each class
    d) Accuracy, macro-average f1 and weighted-average f1 score of the model

    y_actual: numpy array of shape (N,) containing the actual class of each test instance
    y_predicted: numpy array of shape (N,) containing the class of each test instance predicted by the model
    labels: 1D numpy array containing the class labels of the dataset
    filename: name of the output (.csv) file
    '''

    # Open file
    output = open('A1-Output/' + filename + '.csv', 'w')

    # a) Write y values of test data
    output.write('instance,prediction\n')
    for i in range(y_predicted.shape[0]):
        output.write(str(i+1) + ',' + str(y_predicted[i]) + '\n')

    output.write('\n')

    # b) Plot confusion matrix
    output.write('confusion matrix\n')
    confusion_matrix = sklearn.metrics.confusion_matrix(y_actual, y_predicted)
    (m, n) = confusion_matrix.shape
    for i in range(m):
        for j in range(n):
            if j < n-1:
                output.write(str(confusion_matrix[i,j]) + ',')
            else:
                output.write(str(confusion_matrix[i,j]))
        output.write('\n')

    output.write('\n')

    # c) Write precision, recall and f1-measure of each class (rounded to 2 decimals)
    output.write('precision,recall,f1-measure\n')
    precision = sklearn.metrics.precision_score(y_actual, y_predicted, average=None)
    recall = sklearn.metrics.recall_score(y_actual, y_predicted, average=None)
    f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average=None)

    for i in range(labels.shape[0]):
        #output.write(str(precision[i]) + ',' + str(recall[i]) + ',' + str(f1[i]) + '\n')
        output.write('{:.2f},{:.2f},{:.2f}\n'.format(precision[i], recall[i], f1[i]))

    output.write('\n')

    # Write accuracy, macro-average f1 and weighted-average f1 of the model (rounded to 2 decimals)
    output.write('accuracy,macro-average f-1,weighted-average f1\n') 
    accuracy = sklearn.metrics.accuracy_score(y_actual, y_predicted)
    macro_avg_f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average='macro')
    weighted_avg_f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average='weighted')
    #output.write(str(accuracy) + ',' + str(macro_avg_f1) + ',' + str(weighted_avg_f1))
    output.write('{:.2f},{:.2f},{:.2f}\n'.format(accuracy, macro_avg_f1, weighted_avg_f1))

    # Close output file
    output.close()

nb_pixels = 32**2

In [20]:
#Loading training and validation data for both datasets
#dataset 1
ds1_labels = np.loadtxt('Assig1-Dataset/info_1.csv', skiprows=1, usecols=1, delimiter=',', dtype=np.str)

ds1_training_X = np.loadtxt('Assig1-Dataset/train_1.csv', usecols=np.arange(nb_pixels), delimiter=',' ,dtype=np.int32)
ds1_training_Y = np.loadtxt('Assig1-Dataset/train_1.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)

ds1_val_X = np.loadtxt('Assig1-Dataset/val_1.csv', usecols=np.arange(nb_pixels), delimiter=',' ,dtype=np.int32)
ds1_val_Y = np.loadtxt('Assig1-Dataset/val_1.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)

#dataset 2
ds2_labels = np.loadtxt('Assig1-Dataset/info_2.csv', skiprows=1, usecols=1, delimiter=',', dtype=np.str)

ds2_training_X = np.loadtxt('Assig1-Dataset/train_2.csv', usecols=np.arange(nb_pixels), delimiter=',' ,dtype=np.int32)
ds2_training_Y = np.loadtxt('Assig1-Dataset/train_2.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)

ds2_val_X = np.loadtxt('Assig1-Dataset/val_2.csv', usecols=np.arange(nb_pixels), delimiter=',' ,dtype=np.int32)
ds2_val_Y = np.loadtxt('Assig1-Dataset/val_2.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)

In [ ]:
#Gridsearch for best parameters for dataset 1
best_mlp = mlp(max_iter=3500)
parameters = {'hidden_layer_sizes':[(150,100), (50,50), (50,30,50)], 'activation': ['identity', 'relu','tanh','logistic'], 'solver':['adam', 'sgd']}
clf = GridSearchCV(best_mlp, parameters, verbose=5)
clf.fit(ds1_training_X, ds1_training_Y)
print('Best parameters found:\n', clf.best_params_)

In [21]:
#Training Best-MLP model for dataset 1
bestMLP_ds1 = mlp(hidden_layer_sizes=(150,100), activation='logistic',solver='adam', max_iter=4000).fit(ds1_training_X,ds1_training_Y)

In [22]:
#Training model for dataset 1
ds1_val_Y_predict = bestMLP_ds1.predict(ds1_val_X)

#print (sklearn.metrics.confusion_matrix(ds1_val_Y, ds1_val_Y_predict))
print ('\n')
print (sklearn.metrics.classification_report(ds1_val_Y, ds1_val_Y_predict, target_names=ds1_labels)) # precision, recall, f1-measure (macro and weighted) and accuracy



              precision    recall  f1-score   support

           A       0.82      0.90      0.86        10
           B       1.00      0.56      0.71         9
           C       1.00      1.00      1.00        10
           D       1.00      1.00      1.00         8
           E       0.75      0.75      0.75         8
           F       0.60      0.75      0.67         8
           G       0.70      0.70      0.70        10
           H       1.00      0.67      0.80         9
           I       1.00      1.00      1.00        10
           J       0.73      0.80      0.76        10
           K       1.00      1.00      1.00        10
           L       0.91      1.00      0.95        10
           M       0.89      0.80      0.84        10
           N       0.64      0.70      0.67        10
           O       0.89      0.80      0.84        10
           P       0.62      1.00      0.77        10
           Q       0.90      0.90      0.90        10
           R       1.00  

In [13]:
#Gridsearch for best parameters for dataset 2
best_mlp = mlp(max_iter=3500)
parameters = {'hidden_layer_sizes':[(150,100), (50,50), (50,30,50)], 'activation': ['identity', 'relu','tanh','logistic'], 'solver':['adam', 'sgd']}
clf = GridSearchCV(best_mlp, parameters, verbose=5)
clf.fit(ds2_training_X, ds2_training_Y)
print('Best parameters found:\n', clf.best_params_)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=adam .


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=adam, score=0.826, total=  45.7s
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=adam .


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   45.7s remaining:    0.0s


[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=adam, score=0.841, total=  59.3s
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=adam .


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  1.8min remaining:    0.0s


[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=adam, score=0.792, total=  50.2s
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=adam .


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  2.6min remaining:    0.0s


[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=adam, score=0.839, total=  37.0s
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=adam .


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:  3.2min remaining:    0.0s


[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=adam, score=0.807, total=  41.4s
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=sgd ..
[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=sgd, score=0.824, total= 4.5min
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=sgd ..
[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=sgd, score=0.816, total= 4.7min
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=sgd ..
[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=sgd, score=0.817, total= 4.5min
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=sgd ..
[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=sgd, score=0.830, total= 4.0min
[CV] activation=identity, hidden_layer_sizes=(150, 100), solver=sgd ..
[CV]  activation=identity, hidden_layer_sizes=(150, 100), solver=sgd, score=0.808, total= 3.2min
[CV] activation=identity, hidden_layer_sizes=(50, 50), solver=

[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=adam, score=0.873, total=  33.7s
[CV] activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd ....
[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd, score=0.858, total= 1.3min
[CV] activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd ....
[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd, score=0.856, total= 1.4min
[CV] activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd ....
[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd, score=0.863, total= 1.4min
[CV] activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd ....
[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd, score=0.866, total= 1.4min
[CV] activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd ....
[CV]  activation=relu, hidden_layer_sizes=(50, 30, 50), solver=sgd, score=0.860, total= 1.3min
[CV] activation=tanh, hidden_layer_sizes=(150, 100), solver=adam .....
[CV

[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=adam, score=0.888, total=  55.5s
[CV] activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd, score=0.876, total= 7.2min
[CV] activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd, score=0.878, total= 7.7min
[CV] activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd, score=0.881, total= 7.7min
[CV] activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd, score=0.878, total= 7.5min
[CV] activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(50, 50), solver=sgd, score=0.875, total= 8.1min
[CV] activation=logistic, hidden_layer_sizes=(50, 30, 50), solver=adam 
[C

[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed: 877.5min finished


Best parameters found:
 {'activation': 'tanh', 'hidden_layer_sizes': (150, 100), 'solver': 'adam'}


In [14]:
#Training Best-MLP model for dataset 2
bestMLP_ds2 = mlp(hidden_layer_sizes=(150,100), activation='tanh',solver='adam', max_iter=4000,verbose=True).fit(ds2_training_X,ds2_training_Y)

Iteration 1, loss = 1.55694726
Iteration 2, loss = 0.83839082
Iteration 3, loss = 0.62529367
Iteration 4, loss = 0.52204978
Iteration 5, loss = 0.45257151
Iteration 6, loss = 0.41982355
Iteration 7, loss = 0.37526405
Iteration 8, loss = 0.35155650
Iteration 9, loss = 0.33485804
Iteration 10, loss = 0.31522753
Iteration 11, loss = 0.29883234
Iteration 12, loss = 0.27588139
Iteration 13, loss = 0.27639525
Iteration 14, loss = 0.24770119
Iteration 15, loss = 0.23205362
Iteration 16, loss = 0.23918376
Iteration 17, loss = 0.20602213
Iteration 18, loss = 0.19867277
Iteration 19, loss = 0.17311015
Iteration 20, loss = 0.16316145
Iteration 21, loss = 0.15688628
Iteration 22, loss = 0.13137361
Iteration 23, loss = 0.14974627
Iteration 24, loss = 0.11740920
Iteration 25, loss = 0.12209242
Iteration 26, loss = 0.10696555
Iteration 27, loss = 0.10457678
Iteration 28, loss = 0.09109464
Iteration 29, loss = 0.07884886
Iteration 30, loss = 0.06844352
Iteration 31, loss = 0.06339044
Iteration 32, los

In [15]:
#Training model for dataset 2
ds2_val_Y_predict = bestMLP_ds2.predict(ds2_val_X)

print (sklearn.metrics.confusion_matrix(ds2_val_Y, ds2_val_Y_predict))
print ('\n')
print (sklearn.metrics.classification_report(ds2_val_Y, ds2_val_Y_predict, target_names=ds2_labels)) # precision, recall, f1-measure (macro and weighted) and accuracy

[[157   0   0   1   3   0   1   0   2   1]
 [  2 364   0   1   2   2   1   1   1   1]
 [  1   0  32   1   0   2   0   0   7   2]
 [  1   2   0  40   1   0   0   0   0   1]
 [  8   0   1   0 124   6   0   0   1  10]
 [  0   5   0   3   2 150   2   0   0   3]
 [  0   2   0   0   0   0  41   0   1   1]
 [  1   0   0   0   1   1   0  42   0   0]
 [  3   1   2   0   4   0   0   0 137   3]
 [  1   1   2   0   6   6   2   0   4 353]]


              precision    recall  f1-score   support

          pi       0.90      0.95      0.93       165
       alpha       0.97      0.97      0.97       375
        beta       0.86      0.71      0.78        45
       sigma       0.87      0.89      0.88        45
       gamma       0.87      0.83      0.85       150
       delta       0.90      0.91      0.90       165
      lambda       0.87      0.91      0.89        45
       omega       0.98      0.93      0.95        45
          mu       0.90      0.91      0.90       150
          xi       0.94   

In [23]:
#Testing for dataset 1
ds1_test_X = np.loadtxt('Assig1-Dataset/test_no_label_1.csv', delimiter=',' ,dtype=np.int32)
ds1_test_Y = np.loadtxt('Assig1-Dataset/test_with_label_1.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)
ds1_test_Y_predict = bestMLP_ds1.predict(ds1_test_X)

print("DATASET 1\n")
print (sklearn.metrics.confusion_matrix(ds1_test_Y, ds1_test_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds1_test_Y, ds1_test_Y_predict, target_names=ds1_labels)) # precision, recall, f1-measure (macro and weighted average) and accuracy

#Testing for dataset 2
ds2_test_X = np.loadtxt('Assig1-Dataset/test_no_label_2.csv', delimiter=',' ,dtype=np.int32)
ds2_test_Y = np.loadtxt('Assig1-Dataset/test_with_label_2.csv', usecols=nb_pixels, delimiter=',' ,dtype=np.int32)
ds2_test_Y_predict = bestMLP_ds2.predict(ds2_test_X)

print("\n=====================================================\n")
print("DATASET 2\n")
print (sklearn.metrics.confusion_matrix(ds2_test_Y, ds2_test_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds2_test_Y, ds2_test_Y_predict, target_names=ds2_labels)) # precision, recall, f1-measure (macro and weighted average) and accuracy



# Write test results to output file GNB-DS1.csv
create_output_file(ds1_test_Y, ds1_test_Y_predict, ds1_labels, 'Best-MLP-DS1')
create_output_file(ds2_test_Y, ds2_test_Y_predict, ds2_labels, 'Best-MLP-DS2')

DATASET 1

[[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]