In [33]:
# Import useful packages
import numpy as np
import sklearn
import sklearn.naive_bayes
import sklearn.metrics

In [34]:
# Define useful functions
def create_output_file(y_actual, y_predicted, labels, filename):
    '''
    Function for creating the ouput file as specified in the assignment instructions:
    a) instance number and predicted label (number)
    b) Confusion matrix
    c) Precision, recall and f1-measure of each class
    d) Accuracy, macro-average f1 and weighted-average f1 score of the model

    y_actual: numpy array of shape (N,) containing the actual class of each test instance
    y_predicted: numpy array of shape (N,) containing the class of each test instance predicted by the model
    labels: 1D numpy array containing the class labels of the dataset
    filename: name of the output (.csv) file
    '''

    # Open file
    output = open('A1-Output/' + filename + '.csv', 'w')

    # a) Write y values of test data
    output.write('instance,prediction\n')
    for i in range(y_predicted.shape[0]):
        output.write(str(i+1) + ',' + str(y_predicted[i]) + '\n')

    output.write('\n')

    # b) Plot confusion matrix
    output.write('confusion matrix\n')
    confusion_matrix = sklearn.metrics.confusion_matrix(y_actual, y_predicted)
    (m, n) = confusion_matrix.shape
    for i in range(m):
        for j in range(n):
            if j < n-1:
                output.write(str(confusion_matrix[i,j]) + ',')
            else:
                output.write(str(confusion_matrix[i,j]))
        output.write('\n')

    output.write('\n')

    # c) Write precision, recall and f1-measure of each class (rounded to 2 decimals)
    output.write('precision,recall,f1-measure\n')
    precision = sklearn.metrics.precision_score(y_actual, y_predicted, average=None)
    recall = sklearn.metrics.recall_score(y_actual, y_predicted, average=None)
    f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average=None)

    for i in range(labels.shape[0]):
        #output.write(str(precision[i]) + ',' + str(recall[i]) + ',' + str(f1[i]) + '\n')
        output.write('{:.2f},{:.2f},{:.2f}\n'.format(precision[i], recall[i], f1[i]))

    output.write('\n')

    # Write accuracy, macro-average f1 and weighted-average f1 of the model (rounded to 2 decimals)
    output.write('accuracy,macro-average f-1,weighted-average f1\n') 
    accuracy = sklearn.metrics.accuracy_score(y_actual, y_predicted)
    macro_avg_f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average='macro')
    weighted_avg_f1 = sklearn.metrics.f1_score(y_actual, y_predicted, average='weighted')
    #output.write(str(accuracy) + ',' + str(macro_avg_f1) + ',' + str(weighted_avg_f1))
    output.write('{:.2f},{:.2f},{:.2f}\n'.format(accuracy, macro_avg_f1, weighted_avg_f1))

    # Close output file
    output.close()

def load_dataset(filename, nb_pixels=32**2):
    '''
    Function for loading the X and Y data of the passed csv file

    filename: name of the file containing the dataset (ex: train_1)

    Return: 
    X: 2D numpy array containing the value of the features of each instance
    Y: 1D numpy array containing the true class of each instance 
    '''
    data = np.loadtxt('Assig1-Dataset/' + filename + '.csv', delimiter=',', dtype=np.int32)
    return data[:, :nb_pixels], data[:, nb_pixels]


In [35]:
# Load training and validation data for dataset 1
ds1_labels = np.loadtxt('Assig1-Dataset/info_1.csv', skiprows=1, usecols=1, delimiter=',', dtype=np.str)

ds1_training_X, ds1_training_Y = load_dataset('train_1')
ds1_val_X, ds1_val_Y = load_dataset('val_1')

In [36]:
# Train Gaussian NB model for dataset 1
ds1_gaussian_nb_model = sklearn.naive_bayes.GaussianNB().fit(ds1_training_X, ds1_training_Y)

In [37]:
# Use validation data to test first
ds1_val_Y_predict = ds1_gaussian_nb_model.predict(ds1_val_X)

# Check validation metrics and modify hyper-parameters as needed in previous cell
print (sklearn.metrics.confusion_matrix(ds1_val_Y, ds1_val_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds1_val_Y, ds1_val_Y_predict, target_names=ds1_labels)) # precision, recall, f1-measure (macro and weighted) and accuracy


[[ 5  1  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  2  0  0  0  0  0  0
   0  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  6  0  1  0  0  0  0  0  0  0  1  0  1  0  1  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  2  0  0  5  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  5  0  0  0  0  1  0  1  0  0  1  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  2  0  0  0  1  0  0  0  0  0  0  0
   0  0]
 [ 1  1  0  0  0  0  0  4  0  0  0  0  2  0  0  0  0  1  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
   0  0]
 [ 0  1  0  0  0  1  0  0  0  6  0  0  1  0  0  0  1  0  0  0  0  0  0  0
   0  0]
 [ 1  0  0  1  0  0  0  0  0  0  7  0  0  0  0  0  0  1  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 1

In [38]:
# When ready, do testing
ds1_test_X, ds1_test_Y = load_dataset('test_with_label_1')

ds1_test_Y_predict = ds1_gaussian_nb_model.predict(ds1_test_X)

# Check test metrics
print (sklearn.metrics.confusion_matrix(ds1_test_Y, ds1_test_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds1_test_Y, ds1_test_Y_predict, target_names=ds1_labels)) # precision, recall, f1-measure (macro and weighted average) and accuracy

# Write test results to output file GNB-DS1.csv
create_output_file(ds1_test_Y, ds1_test_Y_predict, ds1_labels, 'GNB-DS1')

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [39]:
# Load training and validation data for dataset 2
ds2_labels = np.loadtxt('Assig1-Dataset/info_2.csv', skiprows=1, usecols=1, delimiter=',', dtype=np.str)

ds2_training_X, ds2_training_Y = load_dataset('train_2')
ds2_val_X, ds2_val_Y = load_dataset('val_2')


In [40]:
# Train Gaussian NB model for dataset 2
ds2_gaussian_nb_model = sklearn.naive_bayes.GaussianNB().fit(ds2_training_X, ds2_training_Y)

In [41]:
# Use validation data to test first
ds2_val_Y_predict = ds2_gaussian_nb_model.predict(ds2_val_X)

# Check validation metrics and adjust hyper-parameters as needed in previous cell
print (sklearn.metrics.confusion_matrix(ds2_val_Y, ds2_val_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds2_val_Y, ds2_val_Y_predict, target_names=ds2_labels)) # precision, recall, f1-measure (macro and weighted) and accuracy

[[ 60  11   3  60  29   0   0   0   1   1]
 [ 14 341   2  14   1   2   0   1   0   0]
 [  6   0  29   0   0   1   4   0   2   3]
 [  1   3   1  40   0   0   0   0   0   0]
 [  5   1   6   7  68   4   8   0   1  50]
 [  5   0   4  11   6  91  14   0   2  32]
 [  0   1   0   0   0   0  42   0   1   1]
 [  1   3   0   1   0   0   0  39   0   1]
 [  6   6  65   2   0   1  16   1  48   5]
 [  6   2  10   2  11  19  63   0   1 261]]


              precision    recall  f1-score   support

          pi       0.58      0.36      0.45       165
       alpha       0.93      0.91      0.92       375
        beta       0.24      0.64      0.35        45
       sigma       0.29      0.89      0.44        45
       gamma       0.59      0.45      0.51       150
       delta       0.77      0.55      0.64       165
      lambda       0.29      0.93      0.44        45
       omega       0.95      0.87      0.91        45
          mu       0.86      0.32      0.47       150
          xi       0.74   

In [42]:
# When ready, do testing
ds2_test_X, ds2_test_Y = load_dataset('test_with_label_2')

ds2_test_Y_predict = ds2_gaussian_nb_model.predict(ds2_test_X)

# Check test metrics
print (sklearn.metrics.confusion_matrix(ds2_test_Y, ds2_test_Y_predict)) # confusion matrix
print ('\n')
print (sklearn.metrics.classification_report(ds2_test_Y, ds2_test_Y_predict, target_names=ds2_labels)) # precision, recall, f1-measure (macro and weighted average) and accuracy

# Write test results to output file GNB-DS2.csv
create_output_file(ds2_test_Y, ds2_test_Y_predict, ds2_labels, 'GNB-DS2')

[[ 26   4   1  14   8   1   0   0   1   0]
 [  6 111   1   6   0   1   0   0   0   0]
 [  0   0  12   0   1   0   0   0   1   1]
 [  1   0   0  14   0   0   0   0   0   0]
 [  2   0   1   6  20   2   4   0   0  15]
 [  0   0   1   1   1  34   8   0   0  10]
 [  3   1   0   0   0   0  11   0   0   0]
 [  0   1   0   0   0   0   0  14   0   0]
 [  1   2  26   0   0   0   5   0  15   1]
 [  4   1   1   0   4   7  17   0   0  91]]


              precision    recall  f1-score   support

          pi       0.60      0.47      0.53        55
       alpha       0.93      0.89      0.91       125
        beta       0.28      0.80      0.41        15
       sigma       0.34      0.93      0.50        15
       gamma       0.59      0.40      0.48        50
       delta       0.76      0.62      0.68        55
      lambda       0.24      0.73      0.37        15
       omega       1.00      0.93      0.97        15
          mu       0.88      0.30      0.45        50
          xi       0.77   